# Generated by Django 5.0.4 on 2026-08-26 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=20)),
                ('pays', models.CharField(max_length=100)),
                ('wilaya', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('type_livraison', models.CharField(choices=[('domicile', 'Livraison a domicile (600 DA)'), ('bureau', 'Livraison en bureau Yallidine (370 DA)')], default='domicile', max_length=20)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=600, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirme'), ('expedie', 'Expedie'), ('livre', 'Livre'), ('annule', 'Annule')], default='en_attente', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('color_name', models.CharField(blank=True, max_length=50)),
                ('color_hex', models.CharField(blank=True, max_length=7)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
