# Generated by Django 5.0.4 on 2026-08-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya', models.CharField(max_length=100, unique=True)),
                ('price_domicile', models.DecimalField(decimal_places=2, default=600, max_digits=8)),
                ('price_bureau', models.DecimalField(decimal_places=2, default=370, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarif Livraison',
                'verbose_name_plural': 'Tarifs Livraison',
                'ordering': ['wilaya'],
            },
        ),
    ]
